---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: start-nginx
      become: true
      command: nginx
    - name: reload-nginx
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: Lighthouse | Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Lighthouse | Install epel
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Lighthouse | Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: start-nginx
    - name: Lighthouse | Create nginx config
      become: true
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify: reload-nginx
  roles:
    - lighthouse-role