---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.118.96
      ansible_user: centos

vector:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.118.96
      ansible_user: centos
